#! /bin/sh

printf "Install path [ default ./install ] : "
read INSTALL_DIR
printf "\n"

[ -z $INSTALL_DIR ] && INSTALL_DIR=install

case $INSTALL_DIR in
    /*);;
    *) INSTALL_DIR="$(pwd)/$INSTALL_DIR";;
esac

mkdir -p $INSTALL_DIR

printf "Binplacing configuration files\n"
cp -f configs/* $INSTALL_DIR

printf "Binplacing scripts\n"
cp -f scripts/* $INSTALL_DIR

printf "Binplacing assets"
cp  -rf assets/* $INSTALL_DIR


